fail_fast: true
default_install_hook_types = ["pre-commit", "commit-msg", "pre-push"]

[[repos]]
repo = "local"
hooks = [
    { id = "ruff-format", name = "ruff format", language = "system", entry = "uv run ruff format", types_or = ["python"] },
    { id = "ruff-check", name = "ruff check", language = "system", entry = "uv run ruff check", types_or = ["python"] },
    { id = "ty", name = "ty check", language = "system", entry = "uv run ty check", pass_filenames = false, types = ["python"] },
    { id = "pytest", name = "pytest", language = "system", entry = "uv run pytest -vv", pass_filenames = false, stages = ["pre-push"] },
]

[[repos]]
repo = "builtin"
hooks = [
    { id = "check-yaml" },
]

[[repos]]
repo = "https://github.com/python-jsonschema/check-jsonschema"
rev = "5030dca3047414c338091455ac41803200ec1f0f"  # frozen: 0.37.3
hooks = [
    { id = "check-github-workflows" },
]

[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "v4.4.1"
hooks = [
    { id = "commitizen", stages = ["commit-msg"] },
]
